"""Report generation: results.json, per-pose PDBs, and an interpreted report.md."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Callable, Optional

from .config import DockingConfig, ResolvedFiles
from .docking import DockingResult
from .analysis import Interaction
from .utils import LOG


def affinity_band(affinity: float) -> str:
    """Plain-language interpretation of a Vina affinity score."""
    if affinity <= -9.0:
        return "very strong predicted binding"
    if affinity <= -7.0:
        return "strong predicted binding"
    if affinity <= -5.0:
        return "moderate predicted binding"
    if affinity <= -3.0:
        return "weak predicted binding"
    return "very weak or non-specific predicted binding"


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    LOG.info("Wrote results JSON: %s", path)


def split_poses_to_pdb(
    poses_pdbqt: Path, pose_dir: Path, n: Optional[int] = None
) -> list[Path]:
    """Split a multi-MODEL PDBQT into individual pose_<n>.pdb files."""
    text = poses_pdbqt.read_text(encoding="utf-8")
    models = []
    current = []
    in_model = False
    for line in text.splitlines():
        if line.startswith("MODEL"):
            in_model = True
            current = []
        elif line.startswith("ENDMDL"):
            in_model = False
            models.append(current)
        elif in_model:
            current.append(line)
    pose_dir.mkdir(parents=True, exist_ok=True)
    out_paths = []
    for i, model in enumerate(models, start=1):
        if n is not None and i > n:
            break
        p = pose_dir / f"pose_{i}.pdb"
        body = "\n".join(model) + "\nEND\n"
        p.write_text(body, encoding="utf-8")
        out_paths.append(p)
    LOG.info("Split %d poses into %s", len(out_paths), pose_dir)
    return out_paths


def _format_table(rows: list[tuple]) -> list[str]:
    if not rows:
        return []
    widths = []
    header = [str(c) for c in rows[0]]
    data = [[str(c) for c in r] for r in rows[1:]]
    ncol = len(header)
    for c in range(ncol):
        widths.append(max([len(header[c])] + [len(r[c]) for r in data]))
    lines = []
    header_line = "| " + " | ".join(header[c].ljust(widths[c]) for c in range(ncol)) + " |"
    sep_line = "|" + "|".join("-" * (w + 2) for w in widths) + "|"
    lines.append(header_line)
    lines.append(sep_line)
    for r in data:
        lines.append("| " + " | ".join(r[c].ljust(widths[c]) for c in range(ncol)) + " |")
    return lines


def make_report(
    cfg: DockingConfig,
    files: ResolvedFiles,
    docking: DockingResult,
    interactions: list[Interaction],
    receptor_meta: dict,
    ligand_meta: dict,
    box_dict: dict,
    write_pdbs: Callable[[], list[Path]],
) -> str:
    """Assemble the Markdown report and return its text."""
    L = []
    L.append("# Molecular Docking Report")
    L.append("")
    L.append("*Generated by the molecular-docking-pipeline.*")
    L.append("")

    L.append("## 1. Run summary")
    L.append("")
    rows = [
        ("Property", "Value"),
        ("Receptor", receptor_meta.get("source", "-")),
        ("Ligand", ligand_meta.get("canonical_smiles", cfg.ligand)),
        ("Scoring", cfg.scoring),
        ("Exhaustiveness", str(cfg.exhaustiveness)),
        ("Number of modes", str(cfg.num_modes)),
        ("Seed", str(cfg.seed)),
        ("Vina version", docking.vina_version or "?"),
    ]
    L.extend(_format_table(rows))
    L.append("")

    best = docking.best()
    if best:
        band = affinity_band(best.affinity)
        L.append(f"## 2. Top-ranked pose (pose #{best.index})")
        L.append("")
        L.append(
            f"The best predicted binding affinity is **{best.affinity:.2f} kcal/mol**, "
            f"which indicates **{band}**. More negative values correspond to stronger "
            "predicted binding. This is a *computational* estimate from the AutoDock Vina "
            "scoring function, not a measured binding constant."
        )
        L.append("")
        L.append("All poses ranked by affinity:")
        L.append("")
        rows = [("Pose", "Affinity (kcal/mol)", "RMSD l.b.", "RMSD u.b.")]
        for p in docking.poses:
            rows.append(
                (
                    str(p.index),
                    f"{p.affinity:.2f}",
                    "-" if p.rmsd_lb is None else f"{p.rmsd_lb:.2f}",
                    "-" if p.rmsd_ub is None else f"{p.rmsd_ub:.2f}",
                )
            )
        L.extend(_format_table(rows))
        L.append("")

    L.append("## 3. Predicted interactions (best pose)")
    L.append("")
    if interactions:
        L.append("Residue-level contacts detected against the prepared receptor:")
        L.append("")
        rows = [("Type", "Residue", "Distance (Å)", "Detail")]
        for it in interactions:
            rows.append((it.kind, f"{it.receptor_resname}{it.receptor_resnum}",
                         f"{it.distance_angstrom:.2f}", it.detail))
        L.extend(_format_table(rows))
        L.append("")
        L.append("> Interactions are inferred from geometric distance thresholds and are "
                 "approximate. Hydrogen bonds and salt bridges listed here are based on "
                 "contact distances; confirming them requires visual inspection.")
    else:
        L.append("No specific residue-level interactions were detected within the "
                 "default distance thresholds.")
        L.append("")

    L.append("## 4. Drug-likeness (ADMET-lite — Lipinski rule of five)")
    L.append("")
    admet = ligand_meta.get("admet", {})
    if "error" in admet:
        L.append(f"ADMET-lite could not be computed: {admet['error']}")
    else:
        rows = [
            ("Property", "Value", "Ideal"),
            ("Molecular weight (Da)", str(admet.get("molecular_weight", "?")), "< 500"),
            ("LogP", str(admet.get("logp", "?")), "≤ 5"),
            ("H-bond donors", str(admet.get("hbd", "?")), "≤ 5"),
            ("H-bond acceptors", str(admet.get("hba", "?")), "≤ 10"),
        ]
        L.extend(_format_table(rows))
        vio = admet.get("lipinski_violations", 0)
        L.append("")
        if vio == 0:
            L.append("The ligand **satisfies** the Lipinski rule of five (0 violations).")
        elif vio == 1:
            L.append("The ligand has **1** Lipinski violation — borderline drug-likeness.")
        else:
            L.append(f"The ligand has **{vio}** Lipinski violations — reduced oral drug-likeness "
                     "by this heuristic."
                     if vio > 1 else f"The ligand has **{vio}** Lipinski violation.")
        L.append("")

    L.append("## 5. Output files")
    L.append("")
    files_out = [
        ("results.json", "Structured machine-readable results"),
        ("poses.pdbqt / poses/pose_N.pdb", "All poses (PDBQT + per-pose PDB)"),
        ("receptor.pdbqt / receptor.pdb", "Prepared receptor"),
        ("ligand.pdbqt / ligand.sdf", "Prepared ligand"),
        ("config.txt", "Exact Vina configuration used"),
    ]
    rows = [("File", "Contents")] + list(files_out)
    L.extend(_format_table(rows))
    L.append("")

    L.append("## 6. Interpretation notes & caveats")
    L.append("")
    L.append(
        "- Affinity values are **predicted**, not experimental. They are useful for "
        "relative ranking of compounds, not absolute Kd values."
    )
    L.append("- The search box was " + box_dict.get("description", "auto-derived") + ".")
    L.append("- The receptor was prepared at pH 7.4 with polar hydrogens; protonation of "
             "titratable residues may differ from the biological state.")
    L.append("- Rigid-receptor docking cannot capture induced-fit effects.")
    L.append("")
    L.append("---")
    L.append("*Molecular Docking Pipeline v1.0*")

    text = "\n".join(L)
    files.report_md.write_text(text, encoding="utf-8")
    LOG.info("Wrote report: %s", files.report_md)
    return text


def build_results_dict(
    cfg: DockingConfig,
    docking: DockingResult,
    interactions: list[Interaction],
    receptor_meta: dict,
    ligand_meta: dict,
    box_dict: dict,
    pose_paths: list[Path],
) -> dict:
    return {
        "schema_version": "1.0",
        "config": cfg.to_dict(),
        "receptor": receptor_meta,
        "ligand": ligand_meta,
        "box": box_dict,
        "docking": docking.to_dict(),
        "interactions": [i.to_dict() for i in interactions],
        "pose_files": [str(p) for p in pose_paths],
    }
